### ISSUE TITLE
Add whitelisting to local requests regardless of domain name

### ISSUE THREAD

**Issue by robhei** [wongatech/angular-http-loader#21]
Hi everyone,

I find this module very useful, however I wonder if there is a way to whitelist all domains at once? Or more precisely, my application sends $http requests to a relative path so it works both in the testing and the productive environment. Whitelisting the server's domain doesn't seem to work when making relative requests ...

Additionally, I wonder if it's possible to exclude a certain $http request to a whitelisted domain to avoid the loader to show up? I'm reloading messages every 2 seconds and don't want the loader to show up here.

Cheers,
Rob

**Comment by chrisiconolly** [comment]
Hi,

Is this still an issue you'd like to resolve? 

If I understand you correctly there is actually two requests here, one to whitelist relative requests and one to blacklist certain urls on a whitelisted domain?

Chris

**Comment by robhei** [comment]
Hi Chris,

It is still an issue for me, yes :) Right now, I'm just not loading the module in my messages controller but have to include in separately in all other controllers - being able to blacklist the url of the messages request would make it a lot easier. Also, the ability to whitelist relative paths would make the loader work both locally and on the server - right now I only have the server domain whitelisted and the loader just doesn't show up in the local testing environment.

Rob

**Comment by zazoomauro** [comment]
We can actually add some flag to whitelist relatives requests.
Feel free to PR it if you want. 
Could be a good idea

**Comment by chrisiconolly** [comment]
robhei, the latest version includes a flag to whitelist local requests so that should help your development. Can you explain your blacklist request a little better?

Are you after the ability to black list certain urls on a domain? eg:

.blacklistUrls('google.com', ['dont/show/spinner/on/this/path', 'or/this/one']) ?

**Comment by chrisiconolly** [comment]
Added https://github.com/wongatech/angular-http-loader/issues/28 to track the blacklisting urls request.

**Comment by chrisiconolly** [comment]
Functionality added in v0.1.7
