### ISSUE TITLE
Unable to integrate module (yeoman scaffolding)

### ISSUE THREAD

**Issue by darkhorse2013** [wongatech/angular-http-loader#22]
I am trying to integrate your module into my app

However, when I try to integrate it, I get a white screen.

My code is as follows:

    /* global app:true */
    /* exported app */
    'use strict';
    
    /**
     * @ngdoc overview
     * @name WebAppApp
     * @description
     * # WebAppApp
     *
     * Main module of the application.
     */
    var app = angular
        .module('WebAppApp', [
            'ngAnimate',
            'ngAria',
            'ngCookies',
            'ngMessages',
            'ngResource',
            'ngRoute',
            'ngSanitize',
            'ngTouch',
            'angularUtils.directives.dirPagination',
            'ui.bootstrap',
            'ng.httpLoader'
        ])
        .config(function($routeProvider, $locationProvider) {
            $routeProvider
                .when('/', {
                    templateUrl: 'views/login.html',
                    controller: 'loginCtrl',
                    //  controllerAs: 'login'
                })
                .when('/home', {
                    controller: 'homeCtrl',
                    templateUrl: 'views/home.html',
                    resolve: {
                        "checkLoggedIn": function($location, $cookies, $rootScope) {
                            if (!$cookies.get('globals')) {
                                $location.path('/');
                            }
                        }
                    },
                    //controllerAs: 'home'
                })
                .when('/menteeMentors', {
                    controller: 'menteeMentorsCtrl',
                    templateUrl: 'views/listMentorsMentees.html',
                    resolve: {
                        "checkLoggedIn": function($location, $cookies, $rootScope) {
                            if (!$cookies.get('globals')) {
                                $location.path('/');
                            }
                        }
                    },
                    //controllerAs: 'home'
                })
                .when('/myGoals', {
                    controller: 'myGoalsCtrl',
                    templateUrl: 'views/myGoals.html',
                    resolve: {
                        "checkLoggedIn": function($location, $cookies, $rootScope) {
                            if (!$cookies.get('globals')) {
                                $location.path('/');
                            }
                        }
                    },
                    //controllerAs: 'home'
                })
                .when('/addGoal', {
                    controller: 'myGoalsCtrl',
                    templateUrl: 'views/addGoal.html',
                    resolve: {
                        "checkLoggedIn": function($location, $cookies, $rootScope) {
                            if (!$cookies.get('globals')) {
                                $location.path('/');
                            }
                        }
                    },
                    //controllerAs: 'home'
                })
                .when('/signup', {
                    templateUrl: 'views/signup.html',
                    controller: 'signupCtrl',
                    //controllerAs: 'home'
                })
                .otherwise({
                    redirectTo: '/'
                });
    
            //check browser support
            if (window.history && window.history.pushState) {
                //$locationProvider.html5Mode(true); will cause an error $location in HTML5 mode requires a  tag to be present! Unless you set baseUrl tag after head tag like so: <head> <base href="/">
    
                // to know more about setting base URL visit: https://docs.angularjs.org/error/$location/nobase
    
                // if you don't wish to set base URL then use this
                $locationProvider.html5Mode({
                    enabled: true,
                    requireBase: false
                });
            }
    
        });
    
    .config([
        'httpMethodInterceptorProvider',
        function(httpMethodInterceptorProvider) {
            httpMethodInterceptorProvider.whitelistDomain('validate.jsontest.com');
            httpMethodInterceptorProvider.whitelistDomain('github.com');
        }
    ]);

I am using yeoman scaffolding for AngularJS

**Comment by darkhorse2013** [comment]
Here is the error message:

Uncaught Error: [$injector:modulerr] Failed to instantiate module WebAppApp due to:
Error: [$injector:nomod] Module 'WebAppApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=urbaneWebAppApp
    at REGEX_STRING_REGEXP (http://localhost:9000/bower_components/angular/angular.js:68:12)
    at http://localhost:9000/bower_components/angular/angular.js:1958:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:1882:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:1956:14)
    at http://localhost:9000/bower_components/angular/angular.js:4362:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4346:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4272:11)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1630:20)
    at bootstrap (http://localhost:9000/bower_components/angular/angular.js:1651:12)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=urbaneWebAppApp&p1=…F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1651%3A12)

**Comment by zazoomauro** [comment]
seems to be an WebAppApp module error. Not an Http-loader one
