### ISSUE TITLE
Add the ability to hide the spinner on faults (404/500)

### ISSUE THREAD

**Issue by PeetersJeroen** [wongatech/angular-http-loader#34]
Currently when a web request returns a faultcode the spinner will keep spinning indefinitely. It would be better if the spinner is hidden when all requests are done, faulted or not.

**Comment by PeetersJeroen** [comment]
Found it in the code, sorry for the issue!

**Comment by nabil-boag** [comment]
Glad you found the issue @PeetersJeroen.
