### ISSUE TITLE
Please create NPM package

### ISSUE THREAD

**Issue by moskam** [wongatech/angular-http-loader#36]
As bower is slowly becoming obsolete, please consider creating NPM package for this tool.

**Comment by WuglyakBolgoink** [comment]
@wongatech any news?

**Comment by nabil-boag** [comment]
Hey @WuglyakBolgoink  and @moskam I have raised this issue with the team and we will look at doing this asap.

**Comment by WuglyakBolgoink** [comment]
@nabil-boag  thank you very much!

**Comment by nabil-boag** [comment]
@WuglyakBolgoink here you go: https://www.npmjs.com/package/angular-http-loader
